"""Notification vocabulary."""

from __future__ import annotations

from enum import StrEnum


class NotificationType(StrEnum):
    PROJECT_INVITATION = "PROJECT_INVITATION"
    PROJECT_ACCEPTED = "PROJECT_ACCEPTED"
    PROJECT_DECLINED = "PROJECT_DECLINED"
    MILESTONE_FUNDED = "MILESTONE_FUNDED"
    MILESTONE_SUBMITTED = "MILESTONE_SUBMITTED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    PAYMENT_RELEASED = "PAYMENT_RELEASED"
    CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED"
    CANCELLATION_CONFIRMED = "CANCELLATION_CONFIRMED"
    CANCELLATION_DECLINED = "CANCELLATION_DECLINED"
    OTP_SENT = "OTP_SENT"
    REFUND_ISSUED = "REFUND_ISSUED"
    DISPUTE_RAISED = "DISPUTE_RAISED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    TRUST_SCORE_CHANGED = "TRUST_SCORE_CHANGED"
    RISK_WARNING = "RISK_WARNING"


class NotificationSeverity(StrEnum):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
