"""pending email invitations

Revision ID: 046ad169cb40
Revises: e7b65d607785
Create Date: 2026-08-23 01:02:16.147659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046ad169cb40'
down_revision: Union[str, Sequence[str], None] = 'e7b65d607785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('invited_email', sa.String(length=255), nullable=True))
    op.alter_column('project_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_project_members_invited_email'), 'project_members', ['invited_email'], unique=False)
    op.create_unique_constraint('uq_project_members_project_id_invited_email', 'project_members', ['project_id', 'invited_email'])
    op.create_check_constraint(op.f('ck_project_members_member_has_user_or_email'), 'project_members', 'user_id IS NOT NULL OR invited_email IS NOT NULL')
    op.add_column('projects', sa.Column('invited_receiver_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_projects_invited_receiver_email'), 'projects', ['invited_receiver_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_invited_receiver_email'), table_name='projects')
    op.drop_column('projects', 'invited_receiver_email')
    op.drop_constraint(op.f('ck_project_members_member_has_user_or_email'), 'project_members', type_='check')
    op.drop_constraint('uq_project_members_project_id_invited_email', 'project_members', type_='unique')
    op.drop_index(op.f('ix_project_members_invited_email'), table_name='project_members')
    op.alter_column('project_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('project_members', 'invited_email')
    # ### end Alembic commands ###
