"""upi accounts as a payout destination

Revision ID: 35f5178b88d9
Revises: c40d9c597792
Create Date: 2026-08-24 21:09:28.884073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '35f5178b88d9'
down_revision: Union[str, Sequence[str], None] = 'c40d9c597792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upi_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('vpa', sa.String(length=120), nullable=False),
    sa.Column('holder_name', sa.String(length=120), nullable=False),
    sa.Column(
        'status',
        # Reuses the existing bank_account_status type rather than creating a
        # second one: upi_accounts shares those states by design, and
        # create_type=False stops this migration re-issuing CREATE TYPE.
        postgresql.ENUM(
            'PENDING', 'VERIFIED', 'REJECTED', 'FAILED',
            name='bank_account_status',
            create_type=False,
        ),
        nullable=False,
    ),
    sa.Column('name_match_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('provider_fund_account_id', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_upi_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upi_accounts')),
    sa.UniqueConstraint('user_id', 'vpa', name='uq_upi_account_per_user')
    )
    op.create_index(op.f('ix_upi_accounts_user_id'), 'upi_accounts', ['user_id'], unique=False)
    op.create_index('ix_upi_accounts_vpa', 'upi_accounts', ['vpa'], unique=False)
    op.add_column('payout_requests', sa.Column('upi_account_id', sa.Uuid(), nullable=True))
    op.alter_column('payout_requests', 'bank_account_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_payout_requests_upi_account_id_upi_accounts'), 'payout_requests', 'upi_accounts', ['upi_account_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_payout_requests_ck_payout_one_destination'), 'payout_requests', '(bank_account_id IS NULL) <> (upi_account_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_payout_requests_ck_payout_one_destination'), 'payout_requests', type_='check')
    op.drop_constraint(op.f('fk_payout_requests_upi_account_id_upi_accounts'), 'payout_requests', type_='foreignkey')
    op.alter_column('payout_requests', 'bank_account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('payout_requests', 'upi_account_id')
    op.drop_index('ix_upi_accounts_vpa', table_name='upi_accounts')
    op.drop_index(op.f('ix_upi_accounts_user_id'), table_name='upi_accounts')
    op.drop_table('upi_accounts')
    # ### end Alembic commands ###
