"""payments: bank accounts, upi intents, payouts, google sign-in

Revision ID: c40d9c597792
Revises: 046ad169cb40
Create Date: 2026-08-23 22:15:54.742547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c40d9c597792'
down_revision: Union[str, Sequence[str], None] = '046ad169cb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('holder_name', sa.String(length=120), nullable=False),
    sa.Column('ifsc', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('branch', sa.String(length=160), nullable=False),
    sa.Column('account_last4', sa.String(length=4), nullable=False),
    sa.Column('account_hash', sa.String(length=64), nullable=False),
    sa.Column('account_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'FAILED', name='bank_account_status'), nullable=False),
    sa.Column('name_match_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('provider_fund_account_id', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bank_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('user_id', 'account_hash', name='uq_bank_account_per_user')
    )
    op.create_index('ix_bank_accounts_hash', 'bank_accounts', ['account_hash'], unique=False)
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.create_table('payment_intents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', name='payment_intent_status'), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_order_id', sa.String(length=64), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=True),
    sa.Column('ledger_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_payment_intents_ledger_transaction_id_ledger_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_intents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_intents')),
    sa.UniqueConstraint('provider_order_id', name='uq_payment_intent_order'),
    sa.UniqueConstraint('reference', name=op.f('uq_payment_intents_reference'))
    )
    op.create_index('ix_payment_intents_provider_payment', 'payment_intents', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_user_id'), 'payment_intents', ['user_id'], unique=False)
    op.create_table('payout_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bank_account_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PROCESSING', 'PROCESSED', 'REVERSED', 'FAILED', name='payout_status'), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('provider_payout_id', sa.String(length=64), nullable=True),
    sa.Column('ledger_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_payout_requests_bank_account_id_bank_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_payout_requests_ledger_transaction_id_ledger_transactions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payout_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_requests')),
    sa.UniqueConstraint('reference', name='uq_payout_reference')
    )
    op.create_index('ix_payout_requests_provider', 'payout_requests', ['provider_payout_id'], unique=False)
    op.create_index(op.f('ix_payout_requests_user_id'), 'payout_requests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('google_subject', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_subject'), 'users', ['google_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_subject'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_subject')
    op.drop_index(op.f('ix_payout_requests_user_id'), table_name='payout_requests')
    op.drop_index('ix_payout_requests_provider', table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_index(op.f('ix_payment_intents_user_id'), table_name='payment_intents')
    op.drop_index('ix_payment_intents_provider_payment', table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_index('ix_bank_accounts_hash', table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
