"""wallets and double-entry ledger

Revision ID: e3ec9f860da3
Revises: 1346cd92c387
Create Date: 2026-08-22 20:38:44.894823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ec9f860da3'
down_revision: Union[str, Sequence[str], None] = '1346cd92c387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('account_type', sa.Enum('USER_AVAILABLE', 'USER_PROTECTED', 'USER_PENDING_SETTLEMENT', 'SYSTEM_EXTERNAL_SOURCE', 'SYSTEM_FEES', name='ledger_account_type'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(owner_user_id IS NOT NULL AND account_type IN ('USER_AVAILABLE', 'USER_PENDING_SETTLEMENT', 'USER_PROTECTED')) OR (owner_user_id IS NULL AND account_type IN ('SYSTEM_EXTERNAL_SOURCE', 'SYSTEM_FEES'))", name=op.f('ck_ledger_accounts_owner_matches_account_type')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_ledger_accounts_currency_is_iso_4217')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_ledger_accounts_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_accounts')),
    sa.UniqueConstraint('owner_user_id', 'account_type', 'currency', name='uq_ledger_accounts_owner_user_id_account_type_currency')
    )
    op.create_index(op.f('ix_ledger_accounts_owner_user_id'), 'ledger_accounts', ['owner_user_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('transaction_type', sa.Enum('TOP_UP', 'WITHDRAWAL', 'MILESTONE_FUNDING', 'PAYMENT_RELEASE', 'REFUND', 'FEE', 'ADJUSTMENT', name='ledger_transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('POSTED', 'REVERSED', name='ledger_transaction_status'), server_default='POSTED', nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('receiver_user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reversed_by_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_ledger_transactions_amount_is_positive')),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], name=op.f('fk_ledger_transactions_initiated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], name=op.f('fk_ledger_transactions_receiver_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_transactions_reversed_by_transaction_id_ledger_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_ledger_transactions_sender_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_transactions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_ledger_transactions_idempotency_key'))
    )
    op.create_index('ix_ledger_transactions_created_at', 'ledger_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_milestone_id'), 'ledger_transactions', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_project_id'), 'ledger_transactions', ['project_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_receiver_user_id'), 'ledger_transactions', ['receiver_user_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_sender_user_id'), 'ledger_transactions', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_ledger_transactions_transaction_type'), 'ledger_transactions', ['transaction_type'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('frozen_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets'))
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('ledger_postings',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='ledger_posting_direction'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_ledger_postings_amount_is_positive')),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], name=op.f('fk_ledger_postings_account_id_ledger_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], name=op.f('fk_ledger_postings_transaction_id_ledger_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_postings'))
    )
    op.create_index(op.f('ix_ledger_postings_account_id'), 'ledger_postings', ['account_id'], unique=False)
    op.create_index('ix_ledger_postings_account_id_created_at', 'ledger_postings', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ledger_postings_created_at'), 'ledger_postings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_postings_transaction_id'), 'ledger_postings', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_postings_transaction_id'), table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_created_at'), table_name='ledger_postings')
    op.drop_index('ix_ledger_postings_account_id_created_at', table_name='ledger_postings')
    op.drop_index(op.f('ix_ledger_postings_account_id'), table_name='ledger_postings')
    op.drop_table('ledger_postings')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_ledger_transactions_transaction_type'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_sender_user_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_receiver_user_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_project_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_milestone_id'), table_name='ledger_transactions')
    op.drop_index('ix_ledger_transactions_created_at', table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_ledger_accounts_owner_user_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###
