"""projects milestones cancellation disputes notifications ai

Revision ID: e7b65d607785
Revises: e3ec9f860da3
Create Date: 2026-08-22 20:58:08.699037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b65d607785'
down_revision: Union[str, Sequence[str], None] = 'e3ec9f860da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AWAITING_ACCEPTANCE', 'ACTIVE', 'ON_HOLD', 'UNDER_DISPUTE', 'COMPLETED', 'CANCELLED', 'DECLINED', name='project_status'), server_default='DRAFT', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agreement_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_projects_end_date_after_start_date')),
    sa.CheckConstraint('receiver_id IS NULL OR receiver_id <> client_id', name=op.f('ck_projects_client_and_receiver_differ')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_projects_total_amount_is_positive')),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('fk_projects_client_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_projects_receiver_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index('ix_projects_client_id_status', 'projects', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_projects_receiver_id'), 'projects', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('trust_scores',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='risk_band'), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MODERATE', 'LIMITED', name='confidence_level'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_probability BETWEEN 0 AND 1', name=op.f('ck_trust_scores_risk_probability_in_range')),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_trust_scores_score_in_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trust_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trust_scores'))
    )
    op.create_index(op.f('ix_trust_scores_user_id'), 'trust_scores', ['user_id'], unique=False)
    op.create_index('ix_trust_scores_user_id_created_at', 'trust_scores', ['user_id', 'created_at'], unique=False)
    op.create_table('milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('completion_criteria', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_FUNDING', 'FUNDED', 'IN_PROGRESS', 'SUBMITTED', 'CHANGES_REQUESTED', 'APPROVED', 'PAYMENT_RELEASED', 'DISPUTED', 'CANCELLATION_REQUESTED', 'CANCELLED', name='milestone_status'), server_default='DRAFT', nullable=False),
    sa.Column('revision_limit', sa.Integer(), nullable=False),
    sa.Column('revisions_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funding_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('release_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_milestones_amount_is_positive')),
    sa.CheckConstraint('revisions_used >= 0', name=op.f('ck_milestones_revisions_used_non_negative')),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_milestones_sequence_is_positive')),
    sa.ForeignKeyConstraint(['funding_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_milestones_funding_transaction_id_ledger_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_milestones_release_transaction_id_ledger_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones')),
    sa.UniqueConstraint('project_id', 'sequence', name='uq_milestones_project_id_sequence'),
    sa.UniqueConstraint('release_transaction_id', name=op.f('uq_milestones_release_transaction_id'))
    )
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_index(op.f('ix_milestones_status'), 'milestones', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('CLIENT', 'RECEIVER', name='project_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'REMOVED', name='project_member_status'), server_default='PENDING', nullable=False),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_project_members_invited_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_id_user_id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], name=op.f('fk_risk_signals_transaction_id_ledger_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_risk_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_signals'))
    )
    op.create_index(op.f('ix_risk_signals_created_at'), 'risk_signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_rule'), 'risk_signals', ['rule'], unique=False)
    op.create_index(op.f('ix_risk_signals_user_id'), 'risk_signals', ['user_id'], unique=False)
    op.create_table('cancellation_requests',
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_RECEIVER', 'CONFIRMED', 'DECLINED', 'EXPIRED', 'WITHDRAWN', name='cancellation_status'), server_default='AWAITING_RECEIVER', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('refund_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['users.id'], name=op.f('fk_cancellation_requests_counterparty_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_cancellation_requests_milestone_id_milestones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cancellation_requests_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_transaction_id'], ['ledger_transactions.id'], name=op.f('fk_cancellation_requests_refund_transaction_id_ledger_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_cancellation_requests_requested_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancellation_requests')),
    sa.UniqueConstraint('refund_transaction_id', name=op.f('uq_cancellation_requests_refund_transaction_id'))
    )
    op.create_index(op.f('ix_cancellation_requests_counterparty_id'), 'cancellation_requests', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_cancellation_requests_milestone_id'), 'cancellation_requests', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_cancellation_requests_project_id'), 'cancellation_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_cancellation_requests_status'), 'cancellation_requests', ['status'], unique=False)
    op.create_table('disputes',
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('raised_by_id', sa.Uuid(), nullable=False),
    sa.Column('against_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('WORK_NOT_DELIVERED', 'WORK_INCOMPLETE', 'QUALITY_NOT_AS_AGREED', 'PAYMENT_NOT_RELEASED', 'SCOPE_DISAGREEMENT', 'DEADLINE_MISSED', 'OTHER', name='dispute_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'AWAITING_RESPONSE', 'RESOLVED', 'CLOSED', name='dispute_status'), server_default='OPEN', nullable=False),
    sa.Column('outcome', sa.Enum('RELEASE_TO_RECEIVER', 'REFUND_TO_CLIENT', 'SPLIT', 'NO_ACTION', name='dispute_outcome'), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['against_id'], ['users.id'], name=op.f('fk_disputes_against_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_disputes_milestone_id_milestones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_disputes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], name=op.f('fk_disputes_raised_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_disputes_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes'))
    )
    op.create_index(op.f('ix_disputes_milestone_id'), 'disputes', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_disputes_project_id'), 'disputes', ['project_id'], unique=False)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('milestone_submissions',
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('completion_percentage BETWEEN 0 AND 100', name=op.f('ck_milestone_submissions_completion_percentage_in_range')),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_milestone_submissions_milestone_id_milestones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('fk_milestone_submissions_submitted_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestone_submissions')),
    sa.UniqueConstraint('milestone_id', 'attempt', name='uq_milestone_submissions_milestone_id_attempt')
    )
    op.create_index(op.f('ix_milestone_submissions_milestone_id'), 'milestone_submissions', ['milestone_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('PROJECT_INVITATION', 'PROJECT_ACCEPTED', 'PROJECT_DECLINED', 'MILESTONE_FUNDED', 'MILESTONE_SUBMITTED', 'CHANGES_REQUESTED', 'PAYMENT_RELEASED', 'CANCELLATION_REQUESTED', 'CANCELLATION_CONFIRMED', 'CANCELLATION_DECLINED', 'OTP_SENT', 'REFUND_ISSUED', 'DISPUTE_RAISED', 'DISPUTE_RESOLVED', 'TRUST_SCORE_CHANGED', 'RISK_WARNING', name='notification_type'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'CRITICAL', name='notification_severity'), server_default='INFO', nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_notifications_milestone_id_milestones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notifications_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('analysis_type', sa.Enum('AGREEMENT', 'DISPUTE', 'PAYMENT_RISK', 'SUBMISSION', name='ai_analysis_type'), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('dispute_id', sa.Uuid(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_ai_analyses_dispute_id_disputes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_ai_analyses_milestone_id_milestones'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_analyses_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_ai_analyses_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index(op.f('ix_ai_analyses_analysis_type'), 'ai_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analyses_created_at'), 'ai_analyses', ['created_at'], unique=False)
    op.create_table('dispute_messages',
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_dispute_messages_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], name=op.f('fk_dispute_messages_dispute_id_disputes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispute_messages'))
    )
    op.create_index(op.f('ix_dispute_messages_dispute_id'), 'dispute_messages', ['dispute_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('cancellation_request_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('CANCELLATION', 'PHONE_VERIFICATION', name='otp_purpose'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONSUMED', 'EXPIRED', 'INVALIDATED', name='otp_status'), server_default='ACTIVE', nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('delivered_to', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_otp_verifications_attempts_non_negative')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_otp_verifications_max_attempts_is_positive')),
    sa.ForeignKeyConstraint(['cancellation_request_id'], ['cancellation_requests.id'], name=op.f('fk_otp_verifications_cancellation_request_id_cancellation_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_verifications'))
    )
    op.create_index(op.f('ix_otp_verifications_cancellation_request_id'), 'otp_verifications', ['cancellation_request_id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_cancellation_request_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_dispute_messages_dispute_id'), table_name='dispute_messages')
    op.drop_table('dispute_messages')
    op.drop_index(op.f('ix_ai_analyses_created_at'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_type'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_milestone_submissions_milestone_id'), table_name='milestone_submissions')
    op.drop_table('milestone_submissions')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_project_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_milestone_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_cancellation_requests_status'), table_name='cancellation_requests')
    op.drop_index(op.f('ix_cancellation_requests_project_id'), table_name='cancellation_requests')
    op.drop_index(op.f('ix_cancellation_requests_milestone_id'), table_name='cancellation_requests')
    op.drop_index(op.f('ix_cancellation_requests_counterparty_id'), table_name='cancellation_requests')
    op.drop_table('cancellation_requests')
    op.drop_index(op.f('ix_risk_signals_user_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_rule'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_created_at'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_milestones_status'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index('ix_trust_scores_user_id_created_at', table_name='trust_scores')
    op.drop_index(op.f('ix_trust_scores_user_id'), table_name='trust_scores')
    op.drop_table('trust_scores')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_receiver_id'), table_name='projects')
    op.drop_index('ix_projects_client_id_status', table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
